

networks:
  web:  
    external: false
    ipam:
      config:
        - subnet: 10.0.0.0/24

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - web 

  backend:
    build: 
      context: .
      dockerfile: .Dockerfile.backend
    command: bash -c "python manage.py migrate ; python manage.py migrate --run-syncdb; python manage.py runserver 0.0.0.0:8000"
    image: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
    networks:
      - web

  frontend:
    build: 
      context: .
      dockerfile: .Dockerfile.frontend
    image: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - web
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    depends_on:
      - frontend
      - backend
    networks:
      - web

  celery:
    build: 
      context: .
      dockerfile: .Dockerfile.backend
    command: celery -A backend worker -l info
    image: backend
    depends_on:
      - redis
      - backend
      - frontend
      - db
    networks:
      - web

  proxy:
    image: nginx
    container_name: nginx-test
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - web
    depends_on:
      - redis
      - backend
      - frontend
      - db
      - celery
volumes:
  db-data: {}
